name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Nim  ${{ matrix.os }}
    steps:
    - name: Setup Nim Enviroment
      uses: actions/checkout@v3

    - uses: jiro4989/setup-nim-action@v1
      with:
          nim-version: "stable"

    - name: Install nim dependencies
      run: nimble update && nimble install -y

    - name: Run Tests
      run: nimble test
